In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("loans50k.csv",encoding='latin1')

In [3]:
df.head()

,loanID,amount,term,rate,payment,grade,employment,length,home,income,...,totalBal,totalRevLim,accOpen24,avgBal,bcOpen,bcRatio,totalLim,totalRevBal,totalBcLim,totalIlLim
0,188861,8000.0,36 months,0.14,272.07,C,Warehouseman,3 years,RENT,49966.0,...,48054.0,8100.0,8.0,4369.0,43.0,95.7,60629.0,48054.0,1000.0,52529.0
1,517703,11000.0,36 months,0.10,354.89,B,Vice President,10+ years,MORTGAGE,50000.0,...,265838.0,33400.0,4.0,22153.0,19756.0,37.5,297500.0,11844.0,31600.0,0.0
2,268587,35000.0,36 months,0.15,1220.33,D,Owner/Attorney,10+ years,RENT,360000.0,...,850150.0,83000.0,2.0,121450.0,7686.0,83.2,907300.0,173260.0,83000.0,100000.0
3,579902,20000.0,60 months,0.12,447.83,C,Analyst,2 years,MORTGAGE,60000.0,...,20671.0,14200.0,8.0,1723.0,11061.0,1.2,46964.0,20671.0,11200.0,32764.0
4,617630,12000.0,60 months,0.12,266.88,B,medical technician,10+ years,MORTGAGE,64000.0,...,128034.0,14600.0,3.0,18291.0,5904.0,58.4,134600.0,8475.0,14200.0,0.0

In [4]:
df.isnull().sum()

loanID            0
amount            1
term              1
rate              1
payment           1
grade             1
employment     2785
length         2681
home              1
income            1
verified          1
status            1
reason            1
state             1
debtIncRat        1
delinq2yr         1
inq6mth           1
openAcc           1
pubRec            1
revolRatio       19
totalAcc          1
totalPaid         1
totalBal          1
totalRevLim       1
accOpen24         1
avgBal            1
bcOpen          489
bcRatio         521
totalLim          1
totalRevBal       1
totalBcLim        1
totalIlLim        1
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 32 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   loanID       50000 non-null  int64
 1   amount       49999 non-null  float64
 2   term         49999 non-null  str
 3   rate         49999 non-null  float64
 4   payment      49999 non-null  float64
 5   grade        49999 non-null  str
 6   employment   47215 non-null  str
 7   length       47319 non-null  str
 8   home         49999 non-null  str
 9   income       49999 non-null  float64
 10  verified     49999 non-null  str
 11  status       49999 non-null  str
 12  reason       49999 non-null  str
 13  state        49999 non-null  str
 14  debtIncRat   49999 non-null  float64
 15  delinq2yr    49999 non-null  float64
 16  inq6mth      49999 non-null  float64
 17  openAcc      49999 non-null  float64
 18  pubRec       49999 non-null  float64
 19  revolRatio   49981 non-null  float64
 20  totalAcc     49999 non-null  float64
 21  totalPaid    49999 non-null  float64
 22  totalBal     49999 non-null  float64
 23  totalRevLim  49999 non-null  float64
 24  accOpen24    49999 non-null  float64
 25  avgBal       49999 non-null  float64
 26  bcOpen       49511 non-null  float64
 27  bcRatio      49479 non-null  float64
 28  totalLim     49999 non-null  float64
 29  totalRevBal  49999 non-null  float64
 30  totalBcLim   49999 non-null  float64
 31  totalIlLim   49999 non-null  float64
dtypes: float64(22), int64(1), str(9)
memory usage: 12.2 MB

In [11]:
del(df['loanID'])

In [12]:
df.head()

,amount,term,rate,payment,grade,employment,length,home,income,verified,...,totalBal,totalRevLim,accOpen24,avgBal,bcOpen,bcRatio,totalLim,totalRevBal,totalBcLim,totalIlLim
0,8000.0,36 months,0.14,272.07,C,Warehouseman,3 years,RENT,49966.0,Source Verified,...,48054.0,8100.0,8.0,4369.0,43.0,95.7,60629.0,48054.0,1000.0,52529.0
1,11000.0,36 months,0.10,354.89,B,Vice President,10+ years,MORTGAGE,50000.0,Not Verified,...,265838.0,33400.0,4.0,22153.0,19756.0,37.5,297500.0,11844.0,31600.0,0.0
2,35000.0,36 months,0.15,1220.33,D,Owner/Attorney,10+ years,RENT,360000.0,Verified,...,850150.0,83000.0,2.0,121450.0,7686.0,83.2,907300.0,173260.0,83000.0,100000.0
3,20000.0,60 months,0.12,447.83,C,Analyst,2 years,MORTGAGE,60000.0,Source Verified,...,20671.0,14200.0,8.0,1723.0,11061.0,1.2,46964.0,20671.0,11200.0,32764.0
4,12000.0,60 months,0.12,266.88,B,medical technician,10+ years,MORTGAGE,64000.0,Source Verified,...,128034.0,14600.0,3.0,18291.0,5904.0,58.4,134600.0,8475.0,14200.0,0.0

In [42]:

del(df['length'])

In [14]:
df.drop('verified', axis=1, inplace=True)

In [ ]:

df['length'] = df['length'].str.replace(' years','')

In [27]:
X = df.drop('status', axis=1)
y = df['status']

In [28]:
df.columns

Index(['amount', 'term', 'rate', 'payment', 'grade', 'length', 'home',
       'income', 'status', 'debtIncRat', 'delinq2yr', 'inq6mth', 'openAcc',
       'pubRec', 'revolRatio', 'totalAcc', 'totalBal', 'totalRevLim',
       'accOpen24', 'bcOpen', 'bcRatio', 'totalLim', 'totalRevBal',
       'totalBcLim', 'totalIlLim'],
      dtype='str')

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   amount       49999 non-null  float64
 1   term         49999 non-null  str
 2   rate         49999 non-null  float64
 3   payment      49999 non-null  float64
 4   grade        49999 non-null  str
 5   length       47319 non-null  str
 6   home         49999 non-null  str
 7   income       49999 non-null  float64
 8   status       49999 non-null  str
 9   debtIncRat   49999 non-null  float64
 10  delinq2yr    49999 non-null  float64
 11  inq6mth      49999 non-null  float64
 12  openAcc      49999 non-null  float64
 13  pubRec       49999 non-null  float64
 14  revolRatio   49981 non-null  float64
 15  totalAcc     49999 non-null  float64
 16  totalBal     49999 non-null  float64
 17  totalRevLim  49999 non-null  float64
 18  accOpen24    49999 non-null  float64
 19  bcOpen       49511 non-null  float64
 20  bcRatio      49479 non-null  float64
 21  totalLim     49999 non-null  float64
 22  totalRevBal  49999 non-null  float64
 23  totalBcLim   49999 non-null  float64
 24  totalIlLim   49999 non-null  float64
dtypes: float64(20), str(5)
memory usage: 9.5 MB

In [38]:
col=['amount','rate','payment','income','debtIncRat','delinq2yr','inq6mth','openAcc','pubRec','revolRatio','totalAcc','totalBal','totalRevLim',
       'accOpen24', 'bcOpen', 'bcRatio', 'totalLim', 'totalRevBal',
       'totalBcLim', 'totalIlLim']
for i in col:
   df[i]= df[i].fillna(df[i].median())

In [39]:
df.columns

Index(['amount', 'term', 'rate', 'payment', 'grade', 'length', 'home',
       'income', 'status', 'debtIncRat', 'delinq2yr', 'inq6mth', 'openAcc',
       'pubRec', 'revolRatio', 'totalAcc', 'totalBal', 'totalRevLim',
       'accOpen24', 'bcOpen', 'bcRatio', 'totalLim', 'totalRevBal',
       'totalBcLim', 'totalIlLim'],
      dtype='str')

In [46]:
df.isnull().sum()

amount         0
term           0
rate           0
payment        0
grade          0
home           0
income         0
status         0
debtIncRat     0
delinq2yr      0
inq6mth        0
openAcc        0
pubRec         0
revolRatio     0
totalAcc       0
totalBal       0
totalRevLim    0
accOpen24      0
bcOpen         0
bcRatio        0
totalLim       0
totalRevBal    0
totalBcLim     0
totalIlLim     0
dtype: int64

In [44]:
df['status']

0        Charged Off
1         Fully Paid
2            Current
3         Fully Paid
4            Current
            ...
49995     Fully Paid
49996     Fully Paid
49997    Charged Off
49998     Fully Paid
49999     Fully Paid
Name: status, Length: 50000, dtype: str

In [45]:
col=['status','term','grade','home']

for i in col:
   df[i]= df[i].fillna('unknown',inplace=True)

C:\Users\khair bakhsh\AppData\Local\Temp\ipykernel_1396\396463642.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[i]= df[i].fillna('unknown',inplace=True)

In [47]:
df.head()

,amount,term,rate,payment,grade,home,income,status,debtIncRat,delinq2yr,...,totalAcc,totalBal,totalRevLim,accOpen24,bcOpen,bcRatio,totalLim,totalRevBal,totalBcLim,totalIlLim
0,8000.0,36 months,0.14,272.07,C,RENT,49966.0,Charged Off,30.05,0.0,...,15.0,48054.0,8100.0,8.0,43.0,95.7,60629.0,48054.0,1000.0,52529.0
1,11000.0,36 months,0.10,354.89,B,MORTGAGE,50000.0,Fully Paid,8.74,0.0,...,15.0,265838.0,33400.0,4.0,19756.0,37.5,297500.0,11844.0,31600.0,0.0
2,35000.0,36 months,0.15,1220.33,D,RENT,360000.0,Current,14.50,0.0,...,14.0,850150.0,83000.0,2.0,7686.0,83.2,907300.0,173260.0,83000.0,100000.0
3,20000.0,60 months,0.12,447.83,C,MORTGAGE,60000.0,Fully Paid,14.14,0.0,...,48.0,20671.0,14200.0,8.0,11061.0,1.2,46964.0,20671.0,11200.0,32764.0
4,12000.0,60 months,0.12,266.88,B,MORTGAGE,64000.0,Current,5.14,0.0,...,22.0,128034.0,14600.0,3.0,5904.0,58.4,134600.0,8475.0,14200.0,0.0

In [49]:
df.shape

(50000, 24)

In [50]:
df

,amount,term,rate,payment,grade,home,income,status,debtIncRat,delinq2yr,...,totalAcc,totalBal,totalRevLim,accOpen24,bcOpen,bcRatio,totalLim,totalRevBal,totalBcLim,totalIlLim
0,8000.0,36 months,0.14,272.07,C,RENT,49966.0,Charged Off,30.05,0.0,...,15.0,48054.0,8100.0,8.0,43.0,95.7,60629.0,48054.0,1000.0,52529.0
1,11000.0,36 months,0.10,354.89,B,MORTGAGE,50000.0,Fully Paid,8.74,0.0,...,15.0,265838.0,33400.0,4.0,19756.0,37.5,297500.0,11844.0,31600.0,0.0
2,35000.0,36 months,0.15,1220.33,D,RENT,360000.0,Current,14.50,0.0,...,14.0,850150.0,83000.0,2.0,7686.0,83.2,907300.0,173260.0,83000.0,100000.0
3,20000.0,60 months,0.12,447.83,C,MORTGAGE,60000.0,Fully Paid,14.14,0.0,...,48.0,20671.0,14200.0,8.0,11061.0,1.2,46964.0,20671.0,11200.0,32764.0
4,12000.0,60 months,0.12,266.88,B,MORTGAGE,64000.0,Current,5.14,0.0,...,22.0,128034.0,14600.0,3.0,5904.0,58.4,134600.0,8475.0,14200.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,13000.0,60 months,0.13,298.00,C,OWN,65000.0,Fully Paid,27.53,0.0,...,33.0,55174.0,28800.0,12.0,15385.0,26.0,94757.0,55174.0,20800.0,65957.0
49996,26050.0,60 months,0.22,719.33,F,MORTGAGE,56677.0,Fully Paid,20.30,1.0,...,28.0,257712.0,34300.0,10.0,1541.0,88.3,282755.0,34757.0,13200.0,21215.0
49997,30000.0,60 months,0.10,637.27,B,MORTGAGE,75000.0,Charged Off,14.02,0.0,...,21.0,215131.0,89000.0,3.0,38077.0,14.4,326428.0,24032.0,44500.0,34946.0
49998,7500.0,36 months,0.09,239.10,B,MORTGAGE,52000.0,Fully Paid,30.23,1.0,...,40.0,79454.0,26400.0,5.0,5105.0,66.6,133481.0,23206.0,15300.0,47659.0
49999,12000.0,36 months,0.11,392.81,B,RENT,43680.0,Fully Paid,33.46,0.0,...,12.0,41424.0,5000.0,2.0,497.0,89.0,59280.0,41424.0,4500.0,54280.0

In [51]:
del(df['debtIncRat'])

In [52]:
del(df['delinq2yr'])

In [53]:
df

,amount,term,rate,payment,grade,home,income,status,inq6mth,openAcc,...,totalAcc,totalBal,totalRevLim,accOpen24,bcOpen,bcRatio,totalLim,totalRevBal,totalBcLim,totalIlLim
0,8000.0,36 months,0.14,272.07,C,RENT,49966.0,Charged Off,0.0,11.0,...,15.0,48054.0,8100.0,8.0,43.0,95.7,60629.0,48054.0,1000.0,52529.0
1,11000.0,36 months,0.10,354.89,B,MORTGAGE,50000.0,Fully Paid,2.0,12.0,...,15.0,265838.0,33400.0,4.0,19756.0,37.5,297500.0,11844.0,31600.0,0.0
2,35000.0,36 months,0.15,1220.33,D,RENT,360000.0,Current,1.0,8.0,...,14.0,850150.0,83000.0,2.0,7686.0,83.2,907300.0,173260.0,83000.0,100000.0
3,20000.0,60 months,0.12,447.83,C,MORTGAGE,60000.0,Fully Paid,0.0,12.0,...,48.0,20671.0,14200.0,8.0,11061.0,1.2,46964.0,20671.0,11200.0,32764.0
4,12000.0,60 months,0.12,266.88,B,MORTGAGE,64000.0,Current,0.0,8.0,...,22.0,128034.0,14600.0,3.0,5904.0,58.4,134600.0,8475.0,14200.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,13000.0,60 months,0.13,298.00,C,OWN,65000.0,Fully Paid,0.0,16.0,...,33.0,55174.0,28800.0,12.0,15385.0,26.0,94757.0,55174.0,20800.0,65957.0
49996,26050.0,60 months,0.22,719.33,F,MORTGAGE,56677.0,Fully Paid,1.0,14.0,...,28.0,257712.0,34300.0,10.0,1541.0,88.3,282755.0,34757.0,13200.0,21215.0
49997,30000.0,60 months,0.10,637.27,B,MORTGAGE,75000.0,Charged Off,1.0,11.0,...,21.0,215131.0,89000.0,3.0,38077.0,14.4,326428.0,24032.0,44500.0,34946.0
49998,7500.0,36 months,0.09,239.10,B,MORTGAGE,52000.0,Fully Paid,0.0,18.0,...,40.0,79454.0,26400.0,5.0,5105.0,66.6,133481.0,23206.0,15300.0,47659.0
49999,12000.0,36 months,0.11,392.81,B,RENT,43680.0,Fully Paid,1.0,7.0,...,12.0,41424.0,5000.0,2.0,497.0,89.0,59280.0,41424.0,4500.0,54280.0

In [72]:
df['term'].unique()

<StringArray>
[' 36 months', ' 60 months', 'unknown']
Length: 3, dtype: str

In [71]:
df

,amount,term,rate,payment,grade,home,income,status,inq6mth,openAcc,...,totalAcc,totalBal,totalRevLim,accOpen24,bcOpen,bcRatio,totalLim,totalRevBal,totalBcLim,totalIlLim
0,8000.0,36 months,0.14,272.07,C,RENT,49966.0,Charged Off,0.0,11.0,...,15.0,48054.0,8100.0,8.0,43.0,95.7,60629.0,48054.0,1000.0,52529.0
1,11000.0,36 months,0.10,354.89,B,MORTGAGE,50000.0,Fully Paid,2.0,12.0,...,15.0,265838.0,33400.0,4.0,19756.0,37.5,297500.0,11844.0,31600.0,0.0
2,35000.0,36 months,0.15,1220.33,D,RENT,360000.0,Current,1.0,8.0,...,14.0,850150.0,83000.0,2.0,7686.0,83.2,907300.0,173260.0,83000.0,100000.0
3,20000.0,60 months,0.12,447.83,C,MORTGAGE,60000.0,Fully Paid,0.0,12.0,...,48.0,20671.0,14200.0,8.0,11061.0,1.2,46964.0,20671.0,11200.0,32764.0
4,12000.0,60 months,0.12,266.88,B,MORTGAGE,64000.0,Current,0.0,8.0,...,22.0,128034.0,14600.0,3.0,5904.0,58.4,134600.0,8475.0,14200.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,13000.0,60 months,0.13,298.00,C,OWN,65000.0,Fully Paid,0.0,16.0,...,33.0,55174.0,28800.0,12.0,15385.0,26.0,94757.0,55174.0,20800.0,65957.0
49996,26050.0,60 months,0.22,719.33,F,MORTGAGE,56677.0,Fully Paid,1.0,14.0,...,28.0,257712.0,34300.0,10.0,1541.0,88.3,282755.0,34757.0,13200.0,21215.0
49997,30000.0,60 months,0.10,637.27,B,MORTGAGE,75000.0,Charged Off,1.0,11.0,...,21.0,215131.0,89000.0,3.0,38077.0,14.4,326428.0,24032.0,44500.0,34946.0
49998,7500.0,36 months,0.09,239.10,B,MORTGAGE,52000.0,Fully Paid,0.0,18.0,...,40.0,79454.0,26400.0,5.0,5105.0,66.6,133481.0,23206.0,15300.0,47659.0
49999,12000.0,36 months,0.11,392.81,B,RENT,43680.0,Fully Paid,1.0,7.0,...,12.0,41424.0,5000.0,2.0,497.0,89.0,59280.0,41424.0,4500.0,54280.0

In [74]:
df['term'] = df['term'].str.replace(' months','').astype(str)

In [75]:
df

,amount,term,rate,payment,grade,home,income,status,inq6mth,openAcc,...,totalAcc,totalBal,totalRevLim,accOpen24,bcOpen,bcRatio,totalLim,totalRevBal,totalBcLim,totalIlLim
0,8000.0,36,0.14,272.07,C,RENT,49966.0,Charged Off,0.0,11.0,...,15.0,48054.0,8100.0,8.0,43.0,95.7,60629.0,48054.0,1000.0,52529.0
1,11000.0,36,0.10,354.89,B,MORTGAGE,50000.0,Fully Paid,2.0,12.0,...,15.0,265838.0,33400.0,4.0,19756.0,37.5,297500.0,11844.0,31600.0,0.0
2,35000.0,36,0.15,1220.33,D,RENT,360000.0,Current,1.0,8.0,...,14.0,850150.0,83000.0,2.0,7686.0,83.2,907300.0,173260.0,83000.0,100000.0
3,20000.0,60,0.12,447.83,C,MORTGAGE,60000.0,Fully Paid,0.0,12.0,...,48.0,20671.0,14200.0,8.0,11061.0,1.2,46964.0,20671.0,11200.0,32764.0
4,12000.0,60,0.12,266.88,B,MORTGAGE,64000.0,Current,0.0,8.0,...,22.0,128034.0,14600.0,3.0,5904.0,58.4,134600.0,8475.0,14200.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,13000.0,60,0.13,298.00,C,OWN,65000.0,Fully Paid,0.0,16.0,...,33.0,55174.0,28800.0,12.0,15385.0,26.0,94757.0,55174.0,20800.0,65957.0
49996,26050.0,60,0.22,719.33,F,MORTGAGE,56677.0,Fully Paid,1.0,14.0,...,28.0,257712.0,34300.0,10.0,1541.0,88.3,282755.0,34757.0,13200.0,21215.0
49997,30000.0,60,0.10,637.27,B,MORTGAGE,75000.0,Charged Off,1.0,11.0,...,21.0,215131.0,89000.0,3.0,38077.0,14.4,326428.0,24032.0,44500.0,34946.0
49998,7500.0,36,0.09,239.10,B,MORTGAGE,52000.0,Fully Paid,0.0,18.0,...,40.0,79454.0,26400.0,5.0,5105.0,66.6,133481.0,23206.0,15300.0,47659.0
49999,12000.0,36,0.11,392.81,B,RENT,43680.0,Fully Paid,1.0,7.0,...,12.0,41424.0,5000.0,2.0,497.0,89.0,59280.0,41424.0,4500.0,54280.0

In [98]:
df['term']=pd.to_numeric(df['term'],errors='coerce')

In [99]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   amount        50000 non-null  float64
 1   term          49999 non-null  float64
 2   rate          50000 non-null  float64
 3   payment       50000 non-null  float64
 4   income        50000 non-null  float64
 5   status        50000 non-null  object
 6   inq6mth       50000 non-null  float64
 7   openAcc       50000 non-null  float64
 8   pubRec        50000 non-null  float64
 9   revolRatio    50000 non-null  float64
 10  totalAcc      50000 non-null  float64
 11  totalBal      50000 non-null  float64
 12  totalRevLim   50000 non-null  float64
 13  accOpen24     50000 non-null  float64
 14  bcOpen        50000 non-null  float64
 15  bcRatio       50000 non-null  float64
 16  totalLim      50000 non-null  float64
 17  totalRevBal   50000 non-null  float64
 18  totalBcLim    50000 non-null  float64
 19  totalIlLim    50000 non-null  float64
 20  home_OWN      50000 non-null  bool
 21  home_RENT     50000 non-null  bool
 22  home_unknown  50000 non-null  bool
dtypes: bool(3), float64(19), object(1)
memory usage: 7.8+ MB

In [100]:
df.head()

,amount,term,rate,payment,income,status,inq6mth,openAcc,pubRec,revolRatio,...,accOpen24,bcOpen,bcRatio,totalLim,totalRevBal,totalBcLim,totalIlLim,home_OWN,home_RENT,home_unknown
0,8000.0,36.0,0.14,272.07,49966.0,1,0.0,11.0,0.0,0.55,...,8.0,43.0,95.7,60629.0,48054.0,1000.0,52529.0,False,True,False
1,11000.0,36.0,0.10,354.89,50000.0,0,2.0,12.0,0.0,0.36,...,4.0,19756.0,37.5,297500.0,11844.0,31600.0,0.0,False,False,False
2,35000.0,36.0,0.15,1220.33,360000.0,0,1.0,8.0,0.0,0.83,...,2.0,7686.0,83.2,907300.0,173260.0,83000.0,100000.0,False,True,False
3,20000.0,60.0,0.12,447.83,60000.0,0,0.0,12.0,3.0,0.01,...,8.0,11061.0,1.2,46964.0,20671.0,11200.0,32764.0,False,False,False
4,12000.0,60.0,0.12,266.88,64000.0,0,0.0,8.0,0.0,0.58,...,3.0,5904.0,58.4,134600.0,8475.0,14200.0,0.0,False,False,False

In [108]:
df['home_RENT']=df['home_RENT'].astype(int)
df['home_unknown']=df['home_unknown'].astype(int)
df['home_OWN']=df['home_OWN'].astype(int)

In [123]:
df['status']=pd.to_numeric(df['status'],errors='coerce')

In [110]:
del(df['home_unknown'])

In [114]:
df['term']=df['term'].astype(float)

In [115]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [120]:
X = df.drop('status', axis=1)
y = df['status']

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   amount       50000 non-null  float64
 1   term         49999 non-null  float64
 2   rate         50000 non-null  float64
 3   payment      50000 non-null  float64
 4   income       50000 non-null  float64
 5   status       49185 non-null  float64
 6   inq6mth      50000 non-null  float64
 7   openAcc      50000 non-null  float64
 8   pubRec       50000 non-null  float64
 9   revolRatio   50000 non-null  float64
 10  totalAcc     50000 non-null  float64
 11  totalBal     50000 non-null  float64
 12  totalRevLim  50000 non-null  float64
 13  accOpen24    50000 non-null  float64
 14  bcOpen       50000 non-null  float64
 15  bcRatio      50000 non-null  float64
 16  totalLim     50000 non-null  float64
 17  totalRevBal  50000 non-null  float64
 18  totalBcLim   50000 non-null  float64
 19  totalIlLim   50000 non-null  float64
 20  home_OWN     50000 non-null  int64
 21  home_RENT    50000 non-null  int64
dtypes: float64(20), int64(2)
memory usage: 8.4 MB

In [126]:
from sklearn.preprocessing import StandardScaler

numeric_features = X.select_dtypes(include=['float64', 'int64'])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(numeric_features)

In [127]:
X_scaled

array([[-0.83792595, -0.69377243,  0.21706937, ...,  0.23290415,
        -0.34244489,  1.2410214 ],
       [-0.48612727, -0.69377243, -0.68808407, ..., -0.98038232,
        -0.34244489, -0.80578788],
       [ 2.32826222, -0.69377243,  0.44335774, ...,  1.32936366,
        -0.34244489,  1.2410214 ],
       ...,
       [ 1.74193108,  1.44139485, -0.68808407, ..., -0.17321849,
        -0.34244489, -0.80578788],
       [-0.89655907, -0.69377243, -0.91437243, ...,  0.12041952,
        -0.34244489, -0.80578788],
       [-0.36886104, -0.69377243, -0.46179571, ...,  0.2733478 ,
        -0.34244489,  1.2410214 ]], shape=(50000, 21))

In [133]:
df['status']=df['status'].fillna(df['status'].median)

In [130]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [137]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [136]:
df.isnull().sum()

amount         0
term           0
rate           0
payment        0
income         0
status         0
inq6mth        0
openAcc        0
pubRec         0
revolRatio     0
totalAcc       0
totalBal       0
totalRevLim    0
accOpen24      0
bcOpen         0
bcRatio        0
totalLim       0
totalRevBal    0
totalBcLim     0
totalIlLim     0
home_OWN       0
home_RENT      0
dtype: int64

In [135]:
df['term']=df['term'].fillna(df['term'].median())