In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("laptop.csv")
df

   RAM_GB  Storage_GB  Age  Price
0       8         256    1    800
1      16         512    0   1200
2       8         512    2    700
3      32        1024    1   1800
4      16         256    3    650

In [3]:
from sklearn.preprocessing import StandardScaler
x=df.drop("Price",axis=1)
y=df['Price']
scale= StandardScaler()
x_scaled=scale.fit_transform(x)
x_scaled

array([[-0.91287093, -0.91287093, -0.39223227],
       [ 0.        ,  0.        , -1.37281295],
       [-0.91287093,  0.        ,  0.58834841],
       [ 1.82574186,  1.82574186, -0.39223227],
       [ 0.        , -0.91287093,  1.56892908]])

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)

In [6]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
prediction=model.predict(x_test)

In [ ]:

# 1️⃣ Get input from the user
ram = int(input("Enter Size of ram: "))
rom = int(input("Enter size of rom: "))
age = int(input("Enter Age of the laptop: "))

# 2️⃣ Prepare input as a dataframe or array
import numpy as np
user_input = np.array([[ram,rom ,age]])


user_input_scaled = scale.transform(user_input)

# 4️⃣ Predict using the trained model
predicted_price = model.predict(user_input_scaled)

# 5️⃣ Show result
print(f"Predicted Price of the laptop: ${predicted_price[0]:,.2f}")

Predicted Price of the house: $605.56

c:\Users\khair bakhsh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [7]:
df

   RAM_GB  Storage_GB  Age  Price
0       8         256    1    800
1      16         512    0   1200
2       8         512    2    700
3      32        1024    1   1800
4      16         256    3    650