In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("score.csv")

In [3]:
df.head()

   Age  Gender  Annual_Income  Spending_Score  Purchased
0   23    Male          32000              45          0
1   45  Female          64000              78          1
2   34    Male          58000              60          1
3   25  Female          35000              40          0
4   52    Male          72000              65          1

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])

In [5]:
df

    Age  Gender  Annual_Income  Spending_Score  Purchased
0    23       1          32000              45          0
1    45       0          64000              78          1
2    34       1          58000              60          1
3    25       0          35000              40          0
4    52       1          72000              65          1
5    46       0          69000              70          1
6    29       1          42000              55          0
7    31       0          48000              58          0
8    27       1          39000              52          0
9    41       0          61000              66          1
10   36       1          54000              59          1
11   28       0          43000              54          0
12   33       1          50000              61          1
13   39       0          62000              63          1
14   22       1          30000              42          0
15   44       0          67000              71          1
16   37       1          56000              64          1
17   26       0          36000              47          0
18   30       1          47000              56          0
19   48       0          70000              74          1
20   35       1          52000              62          1
21   24       0          34000              44          0
22   40       1          60000              67          1
23   32       0          49000              57          0
24   38       1          55000              60          1
25   29       0          41000              50          0
26   43       1          65000              72          1
27   27       0          38000              48          0
28   34       0          53000              59          1
29   31       1          46000              55          0

In [32]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
forscalinng=['Age','Gender','Annual_Income','Spending_Score']
scaled=scale.fit_transform(df[forscalinng])
scaled

array([[-1.44433273,  1.        , -1.57452517, -1.40566175],
       [ 1.3676425 , -1.        ,  1.08664413,  2.0389054 ],
       [-0.03834512,  1.        ,  0.58767489,  0.16005059],
       [-1.18869862, -1.        , -1.32504055, -1.92756586],
       [ 2.26236189,  1.        ,  1.75193646,  0.68195471],
       [ 1.49545956, -1.        ,  1.50245184,  1.20385882],
       [-0.6774304 ,  1.        , -0.74290977, -0.36185352],
       [-0.42179628, -1.        , -0.24394052, -0.04871105],
       [-0.93306451,  1.        , -0.99239439, -0.67499599],
       [ 0.85637428, -1.        ,  0.83715951,  0.78633553],
       [ 0.217289  ,  1.        ,  0.25502873,  0.05566977],
       [-0.80524745, -1.        , -0.65974822, -0.46623434],
       [-0.16616217,  1.        , -0.07761744,  0.26443142],
       [ 0.60074016, -1.        ,  0.92032105,  0.47319306],
       [-1.57214979,  1.        , -1.74084826, -1.71880421],
       [ 1.23982544, -1.        ,  1.33612876,  1.30823965],
       [ 0.34510605,  1.        ,  0.42135181,  0.57757389],
       [-1.06088156, -1.        , -1.24187901, -1.1969001 ],
       [-0.54961334,  1.        , -0.32710206, -0.2574727 ],
       [ 1.75109367, -1.        ,  1.58561338,  1.62138211],
       [ 0.08947194,  1.        ,  0.08870564,  0.36881224],
       [-1.31651568, -1.        , -1.40820209, -1.51004257],
       [ 0.72855722,  1.        ,  0.75399797,  0.89071635],
       [-0.29397923, -1.        , -0.16077898, -0.15309187],
       [ 0.47292311,  1.        ,  0.33819027,  0.16005059],
       [-0.6774304 , -1.        , -0.82607131, -0.88375763],
       [ 1.11200839,  1.        ,  1.16980568,  1.41262047],
       [-0.93306451, -1.        , -1.07555593, -1.09251928],
       [-0.03834512, -1.        ,  0.17186718,  0.05566977],
       [-0.42179628,  1.        , -0.4102636 , -0.36185352]])

In [33]:
df.columns

Index(['Age', 'Gender', 'Annual_Income', 'Spending_Score', 'Purchased'], dtype='str')

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             30 non-null     int64
 1   Gender          30 non-null     int64
 2   Annual_Income   30 non-null     int64
 3   Spending_Score  30 non-null     int64
 4   Purchased       30 non-null     int64
dtypes: int64(5)
memory usage: 1.3 KB

In [35]:
df

    Age  Gender  Annual_Income  Spending_Score  Purchased
0    23       1          32000              45          0
1    45       0          64000              78          1
2    34       1          58000              60          1
3    25       0          35000              40          0
4    52       1          72000              65          1
5    46       0          69000              70          1
6    29       1          42000              55          0
7    31       0          48000              58          0
8    27       1          39000              52          0
9    41       0          61000              66          1
10   36       1          54000              59          1
11   28       0          43000              54          0
12   33       1          50000              61          1
13   39       0          62000              63          1
14   22       1          30000              42          0
15   44       0          67000              71          1
16   37       1          56000              64          1
17   26       0          36000              47          0
18   30       1          47000              56          0
19   48       0          70000              74          1
20   35       1          52000              62          1
21   24       0          34000              44          0
22   40       1          60000              67          1
23   32       0          49000              57          0
24   38       1          55000              60          1
25   29       0          41000              50          0
26   43       1          65000              72          1
27   27       0          38000              48          0
28   34       0          53000              59          1
29   31       1          46000              55          0

In [36]:
X = df.drop('Purchased', axis=1)
y = df['Purchased']

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train, X_test, y_train, y_test

(    Age  Gender  Annual_Income  Spending_Score
 28   34       0          53000              59
 24   38       1          55000              60
 12   33       1          50000              61
 0    23       1          32000              45
 4    52       1          72000              65
 16   37       1          56000              64
 5    46       0          69000              70
 13   39       0          62000              63
 11   28       0          43000              54
 22   40       1          60000              67
 1    45       0          64000              78
 2    34       1          58000              60
 25   29       0          41000              50
 3    25       0          35000              40
 21   24       0          34000              44
 26   43       1          65000              72
 18   30       1          47000              56
 29   31       1          46000              55
 20   35       1          52000              62
 7    31       0          48000              58
 10   36       1          54000              59
 14   22       1          30000              42
 19   48       0          70000              74
 6    29       1          42000              55,
     Age  Gender  Annual_Income  Spending_Score
 27   27       0          38000              48
 15   44       0          67000              71
 23   32       0          49000              57
 17   26       0          36000              47
 8    27       1          39000              52
 9    41       0          61000              66,
 28    1
 24    1
 12    1
 0     0
 4     1
 16    1
 5     1
 13    1
 11    0
 22    1
 1     1
 2     1
 25    0
 3     0
 21    0
 26    1
 18    0
 29    0
 20    1
 7     0
 10    1
 14    0
 19    1
 6     0
 Name: Purchased, dtype: int64,
 27    0
 15    1
 23    0
 17    0
 8     0
 9     1
 Name: Purchased, dtype: int64)

C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [48]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

new_customer = [[40,1, 70000, 15]]  # assuming Gender encoded (Male=1)

new_customer = scale.transform(new_customer)

prediction = model.predict(new_customer)

print(prediction)
prediction

[1]

C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [51]:
from  sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
pred=model.predict(X_test)
customer = [[40,1, 80000, 15]]  # assuming Gender encoded (Male=1)

new_customer = scale.transform(customer)

prediction = model.predict(new_customer)

print(prediction)
prediction

[0]

C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# 1. Define X and y (unscaled for now)
X = df.drop('Purchased', axis=1)
y = df['Purchased']

# 2. Split the data FIRST
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Scale the data AFTER splitting
scale = StandardScaler()
X_train_scaled = scale.fit_transform(X_train) # Fit and transform on training data
X_test_scaled = scale.transform(X_test)       # Only transform on test data

# 4. Train the model on the SCALED data
model = LogisticRegression()
model.fit(X_train_scaled, y_train) # That convergence warning should disappear now!

# 5. Predict for your new customer
new_customer = [[40, 1, 70000, 15]] 
new_customer_scaled = scale.transform(new_customer) # Scale using the same scaler
prediction = model.predict(new_customer_scaled)

print(prediction)

[0]

C:\Users\khair bakhsh\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(